name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$HOSTINGER_SSH_KEY" > private_key
          chmod 600 private_key


      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          port: 65002
          script: |
            ssh -p 65002 ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }}
            ${{ secrets.HOSTINGER_SSH_KEY }}
            cd ~/domains/bisque-anteater-166462.hostingersite.com
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear